language: generic

cache:
  directories:
    - ${HOME}/.gem
    - node_modules

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/54033cd9126ab313ec54
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

install:
  - npm install jshint PrettyCSS js-beautify html-linter -g
  - bundle install --path ${HOME}/.gem

script:
  - ./lint.sh
  - bundle exec danger
  - bundle exec jekyll build
